export const DEFAULT_STATIC_COMMAND_CONFIG = {
  streamResponse: false,
  debug: false,
} as const

export const DEVPOD_BINARY = "bin/devpod"
export const DEVPOD_COMMAND_LIST = "list"
export const DEVPOD_COMMAND_STATUS = "status"
export const DEVPOD_COMMAND_UP = "up"
export const DEVPOD_COMMAND_STOP = "stop"
export const DEVPOD_COMMAND_BUILD = "build"
export const DEVPOD_COMMAND_DELETE = "delete"
export const DEVPOD_COMMAND_PROVIDER = "provider"
export const DEVPOD_COMMAND_IDE = "ide"
export const DEVPOD_COMMAND_OPTIONS = "options"
export const DEVPOD_COMMAND_SET_OPTIONS = "set-options"
export const DEVPOD_COMMAND_USE = "use"
export const DEVPOD_COMMAND_INIT = "init"
export const DEVPOD_COMMAND_ADD = "add"
export const DEVPOD_COMMAND_HELPER = "helper"
export const DEVPOD_COMMAND_GET_WORKSPACE_NAME = "get-workspace-name"
export const DEVPOD_COMMAND_GET_PROVIDER_NAME = "get-provider-name"
export const DEVPOD_FLAG_JSON_LOG_OUTPUT = "--log-output=json"
export const DEVPOD_FLAG_JSON_OUTPUT = "--output=json"
export const DEVPOD_FLAG_OPTION = "--option"
export const DEVPOD_FLAG_FORCE_BUILD = "--force-build"
export const DEVPOD_FLAG_RECREATE = "--recreate"
export const DEVPOD_FLAG_IDE = "--ide"
export const DEVPOD_FLAG_PROVIDER = "--provider"
export const DEVPOD_FLAG_ID = "--id"
export const DEVPOD_FLAG_DEBUG = "--debug"
export const DEVPOD_FLAG_USE = "--use"
export const DEVPOD_FLAG_NAME = "--name"
export const DEVPOD_FLAG_SINGLE_MACHINE = "--single-machine"
