version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

    volumes:
      - .:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  app2:
    build:
      context: .
      dockerfile: devcontainer.Dockerfile2
    env_file:
      - .env

    volumes:
      - .:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres-data:
