@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

title Component diagram for Internet Banking System - API Application

Person(user, "DevPod", "CLI or UI")
System(prov, "Kubernetes Provider", "Devpod Provider")
Component(ide, "IDE", "Local IDE")
Component(ctx, "Context", "Config, working dir etc.")
Component(env, "Local Env", "Shell variables, git credentials etc.")

System_Boundary(cluster, "Kubernetes Cluster") {
  System(controlPlane, "kube API server", "Manages the cluster")
  System_Boundary(ns, "devpod namespace") {
    Container_Boundary(ws, "Workspace") {
      Component(runner, "Kaniko runner", "")
      Component(agent, "Agent", "")
      ContainerDb(dir, "Workspace Directory", "Volume", "")
    }
  }
}

BiRel(user, prov, "")
BiRel(prov, controlPlane, "kubectl ...")
Rel(controlPlane, ws, " ")
Rel(agent, runner, " ")
BiRel(agent, ide, "SSH port forwarding")
Rel(user, ide, " ")
Rel(user, ctx, " ")
Rel(user, env, " ")
@enduml